CREATE DATABASE student;

use student;

CREATE TABLE IF NOT EXISTS `class_1`(
   `ID` INT UNSIGNED AUTO_INCREMENT,
   `Name` VARCHAR(10) NOT NULL,
   `Gender` VARCHAR(10) NOT NULL,
   `Age` INT(3) NOT NULL,
   `Tel` INT(100) NOT NULL,
   PRIMARY KEY ( `ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;